export const PERMISSIONS = {
  DASHBOARD: 'dashboard',
  USERS: 'users',
  HOSTS: 'hosts',
  BOOKINGS: 'bookings',
  PRODUCTS: 'trips',
  ORDERS: 'stories',
  BLOGS: 'blogs',
  PAYMENTS: 'payments',
  USER_SUPPORT: 'usersupport',
  SETTINGS: 'settings',
  ADMIN_USERS: 'adminusers',
  ERROR_LOGS: 'errorlogs',
  API_LOGS: 'apilogs',
  API_ANALYTICS: 'apianalytics',
  SECURITY: 'security',
  SERVER_HEALTH: 'serverhealth',
  CONFIGS: 'configs',
  COUPONS: 'coupons',
  SIP_PLANS: 'sipplans',
  EMAILS: 'emails',
  LOCATION_ANALYTICS: 'locationanalytics',
  TRIP_ANALYTICS: 'tripanalytics',
  LINKS: 'links',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];