import { PERMISSIONS, Permission } from "./permissions";

export type Role = "superAdmin" | "admin" | "user"

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
    superAdmin: [
        PERMISSIONS.DASHBOARD,
        PERMISSIONS.USERS,
        PERMISSIONS.HOSTS,
        PERMISSIONS.BOOKINGS,
        PERMISSIONS.PRODUCTS,
        PERMISSIONS.ORDERS,
        PERMISSIONS.PAYMENTS,
        PERMISSIONS.USER_SUPPORT,
        PERMISSIONS.SETTINGS,
        PERMISSIONS.ADMIN_USERS,
        PERMISSIONS.ERROR_LOGS,
        PERMISSIONS.API_LOGS,
        PERMISSIONS.API_ANALYTICS,
        PERMISSIONS.SECURITY,
        PERMISSIONS.SERVER_HEALTH,
        PERMISSIONS.CONFIGS,
        PERMISSIONS.COUPONS,
        PERMISSIONS.EMAILS,
    ],

    admin: [
        PERMISSIONS.DASHBOARD,
        PERMISSIONS.USERS,
        PERMISSIONS.HOSTS,
        PERMISSIONS.BOOKINGS,
        PERMISSIONS.PRODUCTS,
        PERMISSIONS.ORDERS,
        PERMISSIONS.PAYMENTS,
        PERMISSIONS.USER_SUPPORT,
        PERMISSIONS.CONFIGS,
        PERMISSIONS.COUPONS,
        PERMISSIONS.EMAILS,
    ],

    user: [
        PERMISSIONS.DASHBOARD,
    ]
}
 